name: firebase_auth_screen
description: Authentication screen with firebase.
version: 0.0.33
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  crypto: ^3.0.1
  equatable: ^2.0.3
  firebase:
  firebase_auth:
  firebase_core:

  flutter_bloc: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_easyloading: ^3.0.3
  #  flutter_facebook_auth: ^5.0.11
  flutter_otp_text_field: ^1.0.0
  flutter_signin_button: ^2.0.0
  flutter_svg:
  fluttertoast: ^8.0.9
  form_builder_chips_input: ^0.0.3
  google_sign_in: ^5.2.4
  intl_phone_number_input: ^0.7.2
  modal_bottom_sheet:
  sheet: ^0.0.4+1
  sign_button: ^2.0.2
  sign_in_with_apple: ^4.3.0
  sms_autofill: ^2.3.0
  social_login_buttons: ^1.0.7
  top_snackbar_flutter: ^1.0.2
  signature:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/unlock.svg
