name: firebase_auth_screen
description: Authentication screen with firebase.
version: 0.0.14
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.0.3
  crypto: ^3.0.1
  equatable: ^2.0.3
  firebase: ^9.0.2
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_easyloading: ^3.0.3
  flutter_facebook_auth: ^4.1.1
  flutter_otp_text_field: ^1.0.0
  flutter_signin_button: ^2.0.0
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  form_builder_chips_input: ^0.0.3
  google_sign_in: ^5.2.4
  intl_phone_number_input: ^0.7.0+2
  modal_bottom_sheet:
  sheet:
  sign_button: ^2.0.2
  sign_in_with_apple: ^3.3.0
  top_snackbar_flutter: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/unlock.svg
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
